User\ExamBundle\Entity\UserManagement:
    properties:
        firstname:
            - NotBlank: {message:'Please enter your firstname'}
        password:
            - Length:
                max: 6
                maxMessage: "Your first name cannot be longer than {{ limit }} characters long"