User\ExamBundle\Entity\Author\UserManagement:
    properties:
        email:
            - Email:
                message: The email "{{ value }}" is not a valid email."

        firstname:
        	- NotBlank: ~

